version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: lint
          command: flake8
      - run:
          name: run tests
          command: pytest
  
  build-and-push-to-dockerhub:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
          docker build -t klm9/oc-lettings-klm:$TAG .
          docker tag klm9/oc-lettings-klm:$TAG klm9/oc-lettings-klm:latest
          docker push klm9/oc-lettings-klm:$TAG
          docker push klm9/oc-lettings-klm:latest
  
  deploy-heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker
      - run:
          name: Push to heroku
          command:  |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ${HEROKU_APP_NAME} web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ${HEROKU_APP_NAME} web

workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint
      - build-and-push-to-dockerhub:
          requires:
            - test-and-lint
          filters:
            branches:
              only: 
                - master
      - deploy-heroku:
          requires:
            - build-and-push-to-dockerhub
          filters:
            branches:
              only:
                - master  